# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "CXG+KIDOZLk2+DKkHgp04z/M11qPyPL5Px9NAEQcTTwSsf7bvbAlZpJVacJ1x0cUQ5MKiHtM/QnoWl0y27+GjZvwhyTw95uuoyh3l/l3BtHhaJQh8NlGYtZYcbx3f2zl98Wc2VqMFtLSXbE+bHXLwbvf0lcQbiDZPZM9igRkjkRYST8od1oO9nM7wr3fU6YMtIDGK0yHc9qi/tuTMJW+bI1NypK0ACFIwyN7HU9bcbC9KuYxgjfdf8ENvHwySD/GoNDPLqUit3yluKhOqNxkNpbUKRm0XH/HpleCT3bJkk9uAUcyC5g7H1DfYpYslI+Xl37Q5MbrsDP6EPI1OrAslfoVrDv+39K2aqtsWY3MWRKz4aT83a8aiA39l+/+BMzO0QYxLKFra1TC/gkLZZyYZXJ2pxTd6VkqJg+Tfx1/pfqLjwSFvNfXgii1PrLKQtiDgV4OQWbGOFYdf0L0A4IRMMrjZr+JmaGaeIpLKsH1mcRIhumwdWbiDuHnW+79rJBDFd6j4vuKTE7XiJc7WKlC1qhp1DBpjZBA4bjxU7g91CYvcgRo2w9m7WQdQkPf8Q5NLw6RJCAAiL1KeFl5WY06Z2KLTjno+/1NlTcqf2FGTMjyUY4X1diCPDnv5+PWJln/aqga+gIKkRgqfgNRSL5N+4CmToAMaIVku1P4DR82r1E="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
