travis:
  secure:
    BINSTAR_TOKEN: 0QX2ozDTXKyzDwe7EuYNP+g08UGXme4x8325aVJp1EQ5VA95MwZEAmCnzvnLavz5UsdHlSPqm+c50IY1kNhxeYFXK9sTzfu7GtdWQE2pnGNZjOZD+WwOPptw+vfccbnzPQXBeSi99oordXszx+TT2vShlA3uk+v730n8YpOYJwoXUGK5GsCPt/tHrvFvsxn0vK86Oy99pCRth8WnReFdMwDF4LQab7UL06UV+459EmIzSPnQcDsCRm14PojHBu9CMrN1raLfEnSZTDhCaaRuDw5ka6EUIj905O/xIjlmBKh6B8V29Nze4KmdC2K1cdwrF2bPk42uLs5xJEo5BsvzVuDlW0oDSTLM8NXvhct2hadt+CVGk9cnqH01r2Nvx2bX3zlwy49lSj1ImJVRuiX4egRG4JCmEq/cQZ2XjWnncbAZNrcc0mGSb4Zi2jhqz9gD0HHl4Kr2jy1/8fLgtEjv4YW5uqTy99TNgfgDNBn439+zbvFgCSBgNqBrXzCYm0fb+HoVhVDbaHmh3HXEgEy7gqgi/KzaHD1UIXj7ubrmezxZTnWRcMDcQQJUo7e03DYOOA0y6T89ATofYmWs3Yu/xPZ+O1JoeT2dXaWeenCJzrRQBrK9ZuTQRa7Mple15muvITEYFNSnpvdluMr2fsdJvpUZvAJX0PPdqAE4mlLJDLg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
