travis:
  secure:
    BINSTAR_TOKEN: 8ch/8X6K55ClfAYz4GW4a+1/1VC+8S9MkIZPGIbn+khS/HIiTAUMMuV1LwkQQCT1KoFrBNnmRG1goGQBoNRXGVtD0eHRg7LRD5HICTZlwbagDTfoaAEDHQyvRdn7WNXBZnZJTvkf/Md01pDQOiEcH3ieczzERvahEZKeA1J4W8k3uhKcAcGemtK4PJgiN1+5Bwtqb9NqQ8p+SHfNUi5j8iWXlGrGY7GUq5UBXFUtUvHUpXAYrnC+MGJcIShzlB6bhukhqzOyLcyDZLrqjvYzl+YXMy9JqF5e20Uv00rUC5q9n97ooyYuymOj/6bDkj9JduUtGABUPG1XL/mG3ZAMrdjcEncX74gdf/6on7D/9UvoIm/SYm0/rqBVlRuIFIvlggYqSrbdP4KePpYrjkIR2U5i46ikWDNGQfn6t06NY2kjvzKFM6+6pOgK2cjcJhF2/Fl+qTPy6Xpxy/UPbCRcflyAVxj3PARjTVF9S1gBGlnIXuat9IF/ukwJG43ucEEP2aUVQ9dWTjQ7UvLxt3i72if7TRMF+ewsYcIzSqw31F9uVuMIC7S6smQgYK1IgnZnIX939/d0bw2SR7q2OocJszt7AWv1Hlq0EE2qJoC43PNVnJ0VmVy9/Qcw2RdSfUVnfh1AsCUbjNUvByUTyFEL4Rogr5xq5ZlxNTEcyfMCodk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
